<Project>
  <PropertyGroup>
    <Copyright>Copyright © 2013-$([System.DateTime]::Now.Year) Akka.NET Team</Copyright>
    <Authors>Akka.NET Team</Authors>
    <VersionPrefix>1.5.18</VersionPrefix>
    <PackageIconUrl>http://getakka.net/images/akkalogo.png</PackageIconUrl>
    <PackageProjectUrl>https://github.com/akkadotnet/Alpakka</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <LangVersion>10.0</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetIsMono Condition="'$(TargetFramework)' == '$(NetFrameworkLibVersion)' and '$(OS)' == 'Unix'">true</TargetIsMono>
    <NoWarn>$(NoWarn);CS1591;xUnit1013</NoWarn>
    <AkkaPackageTags>akka;actors;actor model;Akka;concurrency;streams</AkkaPackageTags>
  </PropertyGroup>
  <PropertyGroup>
    <NetStandardLibVersion>netstandard2.0</NetStandardLibVersion>
    <NetLibVersion>net6.0</NetLibVersion>
    <NetTestVersion>net9.0</NetTestVersion>
    <NetFrameworkTestVersion>net48</NetFrameworkTestVersion>
  </PropertyGroup>
  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <PropertyGroup>
    <PackageReleaseNotes>Bumped to [Akka.NET v1.5.18](https://github.com/akkadotnet/akka.net/releases/tag/1.5.18)
[Akka.Streams.Ampq.RabbitMq: NullReferenceException - when using Akka.Net v1.5.12 and Akka.Streams.Amqp.RabbitMq v1.5.8](https://github.com/akkadotnet/Alpakka/issues/1659)
[Akka.Streams.Ampq.RabbitMq: added publisher confirms functionality to RabbitMQ](https://github.com/akkadotnet/Alpakka/pull/1906)
Merged Akka.Streams.SignalR and Akka.Streams.SignalR.AspNetCore; dropped all non-ASP.NET Core functionality. Will issue a package deprecation warning for Akka.Streams.SignalR.AspNetCore.</PackageReleaseNotes>
  </PropertyGroup>
  <!-- SourceLink support for all Akka.NET projects -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>
  <PropertyGroup>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>