<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>$(NetTestVersion);$(NetFrameworkTestVersion)</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Akka.Streams.TestKit" />
        <PackageReference Include="Akka.TestKit.Xunit2" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="coverlet.collector" />
    </ItemGroup>

    <ItemGroup>
        <None Include="resources\correctness.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="resources\google-docs.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Include="resources\numbers-utf-8.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Akka.Streams.Csv\Akka.Streams.Csv.csproj" />
    </ItemGroup>

</Project>
